
name: Android AAB (gera .aab)
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Cache Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build Release AAB
        run: ./gradlew :app:bundleRelease || ./gradlew :app:bundleRelease
      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app/build/outputs/bundle/release/*.aab
