
name: Android APK (gera .apk)

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Gradle Build Action (no wrapper)
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.7
          cache-read-only: false

      - name: Build Debug APK
        run: |
          gradle :app:assembleDebug
          ls -lah app/build/outputs/apk/debug/

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: iboplus-debug-apk
          path: app/build/outputs/apk/debug/*.apk
