name: Android APK

on:
  workflow_dispatch:   # permite rodar manual
  push:
    branches: [ "main" ]   # continua rodando no push também

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v3

      - name: Build APK
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: IBOPlus-APK
          path: app/build/outputs/apk/debug/app-debug.apk
