name: Android APK

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Gradle (cache)
        uses: gradle/actions/setup-gradle@v3

      # Desabilita configuration cache SÓ aqui, para o task :wrapper
      - name: Generate Gradle Wrapper
        run: |
          gradle --no-configuration-cache wrapper --gradle-version 8.7
          chmod +x gradlew

      # Também sem configuration cache por segurança
      - name: Build Debug APK
        run: ./gradlew --no-configuration-cache :app:assembleDebug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: IBOPlus-APK
          path: app/build/outputs/apk/debug/app-debug.apk
