name: build-apk

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install apktool & build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y apksigner zipalign
          APKTOOL_URL="https://raw.githubusercontent.com/iBotPeaches/Apktool/master/scripts/linux/apktool"
          APKTOOL_JAR_URL="https://github.com/iBotPeaches/Apktool/releases/download/v2.9.3/apktool_2.9.3.jar"
          sudo curl -L "$APKTOOL_URL" -o /usr/local/bin/apktool
          sudo curl -L "$APKTOOL_JAR_URL" -o /usr/local/bin/apktool.jar
          sudo chmod +x /usr/local/bin/apktool

      - name: Prepare project (apktool layout)
        run: |
          set -e
          ls -la
          test -f AndroidManifest.xml
          for d in assets lib original res unknown smali smali_classes2 smali_classes3 META-INF; do
            test -d "$d" && echo "✓ found $d"
          done
          # Remover assinatura antiga (se existir)
          rm -f META-INF/CERT.RSA META-INF/CERT.DSA META-INF/MANIFEST.MF || true

      - name: Build with apktool
        run: |
          set -e
          # apktool b . -o app-unsigned.apk
          # Forçar aapt2 para melhor compatibilidade
          apktool b . -f -o app-unsigned.apk

      - name: Zipalign
        run: |
          zipalign -v -p 4 app-unsigned.apk app-aligned.apk

      - name: Create debug keystore (if not exists)
        run: |
          if [ ! -f debug.keystore ]; then
            keytool -genkeypair -v -keystore debug.keystore -storepass android -keypass android \
              -alias androiddebugkey -dname "CN=Android Debug,O=Android,C=US" -keyalg RSA -keysize 2048 -validity 10000
          fi

      - name: Sign APK
        run: |
          apksigner sign --ks debug.keystore --ks-pass pass:android --key-pass pass:android --out app-signed.apk app-aligned.apk
          apksigner verify app-signed.apk

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: IBOPlus-Clone-1to1
          path: app-signed.apk
